# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"transmission": "02_transparent-thinking.ipynb",
         "kaleidoscope": "02_transparent-thinking.ipynb",
         "optical_density": "02_transparent-thinking.ipynb",
         "primaries": "02_transparent-thinking.ipynb",
         "palette_plot": "02_transparent-thinking.ipynb",
         "Stratigraphy": "02_transparent-thinking.ipynb",
         "reflectance": "10_Color-physics-of-translucent-inks.ipynb",
         "fetch_star": "20_downloading-demo-data.ipynb",
         "fetch_blackwhite": "20_downloading-demo-data.ipynb",
         "GOODBOY": "20_downloading-demo-data.ipynb",
         "registry_file": "20_downloading-demo-data.ipynb"}

modules = ["transparent.py",
           "rgbkm.py",
           "data.py"]

doc_url = "https://fligt.github.io/inktime/"

git_url = "https://github.com/fligt/inktime/tree/master/"

def custom_doc_links(name): return None
