# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"reflectance": "00_rgbkm.ipynb"}

modules = ["rgbkm.py"]

doc_url = "https://fligt.github.io/inktime/"

git_url = "https://github.com/fligt/inktime/tree/master/"

def custom_doc_links(name): return None
